//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Spec.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSpec.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}) {1} - {2}.
        /// </summary>
        internal static string ConsoleFormatteErrorsMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatteErrorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished in {0} seconds.
        /// </summary>
        internal static string ConsoleFormatterElapsedTimeMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatterElapsedTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string ConsoleFormatterErrorMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string ConsoleFormatterSuccessMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatterSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} examples, {1} failures.
        /// </summary>
        internal static string ConsoleFormatterSummaryMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatterSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string DocumentationConsoleFormatterErrorMessage {
            get {
                return ResourceManager.GetString("DocumentationConsoleFormatterErrorMessage", resourceCulture);
            }
        }

        internal static string ConsoleFormatteFailureMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatteFailureMessage", resourceCulture);
            }
        }

        internal static string ConsoleFormatteFailuresMessage {
            get {
                return ResourceManager.GetString("ConsoleFormatteFailuresMessage", resourceCulture);
            }
        }

        internal static string ExampleGroupErrorMessage {
            get {
                return ResourceManager.GetString("ExampleGroupErrorMessage", resourceCulture);
            }
        }
        
        internal static string ExampleErrorMessage {
            get {
                return ResourceManager.GetString("ExampleErrorMessage", resourceCulture);
            }
        }
    }
}
